fakturoid_type:
    tab: Fakturoid
    label: Typ platby ve Fakturoidu
    type: dropdown
    options:
        '': --- vyberte typ platby ---
        bank: Bankovní převod
        cash: Hotově
        cod: Dobírka
        paypal: PayPal
        card: Karta
