# ===================================
#  Form Field Definitions
# ===================================

additional_properties_company_reg_no:
    tab: Dodatečná pole
    label: IČO
    comment: 'Lovata.OrdersShopaholic additional property kód (code) pro IČO'
additional_properties_company_vat_no:
    tab: Dodatečná pole
    label: DIČ
    comment: 'Lovata.OrdersShopaholic additional property kód (code) pro DIČ'
additional_properties_user_due_date_days:
    tab: Dodatečná pole
    label: Splatnost faktur
    comment: 'Lovata.Buddies additional property kód (code) pro Splatnost faktur'

settings_redirect_to_list:
    tab: Nastavení
    label: Přesměrovat na výpis objednávek
    comment: 'Po odeslání do Fakturoidu přesměrovat na výpis všech objednávek'
    type: checkbox
